import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './features/game/App.tsx'
import './index.css'
import {
  createBrowserRouter,
  RouterProvider,
  // Route,
  // Link,
} from "react-router-dom";
import { Helmet } from "react-helmet"
import { ApolloProvider } from '@apollo/client';
import { getClient } from './features/game/gql/getApolloClient.ts';
import { Config } from './features/config/index.tsx';

const router = createBrowserRouter([
  {
    path: "/",
    element: <App />,
  },
  {
    path: "about",
    element: <div>About</div>,
  },
  {
    path: "config",
    element: <Config />,
  },
]);

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <ApolloProvider client={getClient()}>
      <Helmet>
        <title>JAX Mit Materna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Helmet>
      <RouterProvider router={router} />
    </ApolloProvider>
  </React.StrictMode>,)

// createRoot(document.getElementById("root")).render(
//   <RouterProvider router={router} />
// );