"use client";

import Head from "next/head";

import { WheelPartArrayElementTable } from "@/Configuration/WheelParts/WheelPartArrayElement.generated";
import { queryDisplaysettings } from "@/Configuration/mutations/updateDisplaySettings";
import { getwheels } from "@/Wheel/gql/getwheels";
import { toggleDisableWheelValue } from "@/Wheel/gql/toggleDisableWheelValue";
import { getClient } from "@/gql/getApolloClient";
import { useMutation, useQuery } from "@apollo/client";
import { AppContext } from "next/app";
import Link from "next/link";
import { UpdateDisplaySettingsForm } from "@/Configuration/DisplaySettings/DisplaySettings.generated";

export async function getServerSideProps(context: AppContext["ctx"]) {
  const c = getClient(null, true);
  // caching
  await c.query({ query: getwheels });

  return {
    props: { state: c.extract() }, // will be passed to the page component as props
  };
}

export default function WheelParts() {
  const { data } = useQuery(getwheels);
  const [toggleDisabled] = useMutation(toggleDisableWheelValue);
  const { data: displaySettings } = useQuery(queryDisplaysettings);

  return (
    <>
      <Head>
        <title>JAX Mit Materna - Konfiguration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ padding: 16 }}>
        <h1>Einstellungen</h1>
        <div style={{ marginBottom: 12 }}>
          <Link href="/">🏠 Zurück zum Rad</Link>
        </div>

        <h2>Abschnitte</h2>
        <WheelPartArrayElementTable
          onRowClicked={async (item) => {
            await toggleDisabled({ variables: { name: item.name } });
          }}
          items={data?.wheelParts || []}
        />

        <h2>Anzeigeeinstellungen</h2>

        {displaySettings?.displaySettings ? (
          <UpdateDisplaySettingsForm
            item={displaySettings.displaySettings}
            onSave={()=>{}}
          />
        ) : (
          <></>
        )}
        {/* <App values={data?.wheelParts ?? []} /> */}
      </main>
    </>
  );
}
