"use client";

import Head from "next/head";

import { WheelPartArrayElementTable } from "@/Configuration/InForm/WheelPartArrayElement.generated";
import { getwheels } from "@/Wheel/gql/getwheels";
import { toggleDisableWheelValue } from "@/Wheel/gql/toggleDisableWheelValue";
import { getClient } from "@/gql/getApolloClient";
import { useMutation, useQuery } from "@apollo/client";
import { AppContext } from "next/app";

export async function getServerSideProps(context: AppContext["ctx"]) {
  const c = getClient(null, true);
  // caching
  await c.query({ query: getwheels });
  console.log("CACHE SERVERSIDE", {e: c.extract()})

  return {
    props: { state: c.extract() }, // will be passed to the page component as props
  };
}

export default function WheelParts() {
  const { data } = useQuery(getwheels);
  const [toggleDisabled, {}] = useMutation(toggleDisableWheelValue);

  return (
    <>
      <Head>
        <title>JAX Mit Materna - Konfiguration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WheelPartArrayElementTable
          onRowClicked={async (item) => {
            await toggleDisabled({ variables: { name: item.name } });
          }}
          items={data?.wheelParts || []}
        />
        {/* <App values={data?.wheelParts ?? []} /> */}
      </main>
    </>
  );
}
