"use client";

import App from "@/Wheel/App";
import Head from "next/head";

import { getme } from "@/Wheel/gql/getme";
import { getwheels } from "@/Wheel/gql/getwheels";
import { getClient } from "@/gql/getApolloClient";
import { useQuery } from "@apollo/client";
import { AppContext } from "next/app";
import { queryDisplaysettings } from "@/Configuration/mutations/queryDisplaysetting";

export async function getServerSideProps(context: AppContext["ctx"]) {
  const c = getClient(null, true);

  // caching
  await c.query({ query: getme });
  await c.query({
    query: getwheels,
    variables: { filter: { disabled: false } },
  });
  await c.query({ query: queryDisplaysettings });

  return {
    props: { state: c.extract() }, // will be passed to the page component as props
  };
}

export default function AppComponent() {
  const { data, called, loading } = useQuery(getwheels, {
    variables: { filter: { disabled: false } },
    // pollInterval: 1000,
    fetchPolicy: "cache-and-network"
  });

  return (
    <>
      <Head>
        <title>JAX Mit Materna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!called || loading ?
          <></> :
          <App values={data?.wheelParts ?? []} />
        }
      </main>
    </>
  );
}
